name: Build and Package THJInstaller

on:
  workflow_dispatch: #

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Find .csproj File
        id: find_csproj
        shell: pwsh
        run: |
          $csprojPath = Get-ChildItem -Path . -Recurse -Filter "THJPatcher.csproj" | Select-Object -First 1 -ExpandProperty FullName
          if (-not $csprojPath) { throw "THJPatcher.csproj not found!" }
          echo "CSPROJ_PATH=$csprojPath" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Found .csproj at: $csprojPath"

      - name: Extract Version from .csproj
        id: get_version
        shell: pwsh
        run: |
          [xml]$csproj = Get-Content $env:CSPROJ_PATH
          $version = $csproj.Project.PropertyGroup.Version
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Extracted Version: $version"


      - name: Restore dependencies
        run: dotnet restore

      - name: Build the Installer
        run: dotnet publish -c Release -o output /p:EnableWindowsTargeting=true

      - name: Create ZIP
        run: |
          Compress-Archive -Path output\* -DestinationPath THJInstaller-${{ env.VERSION }}.zip
        shell: pwsh

      - name: Upload ZIP as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: THJInstaller-ZIP
          path: THJInstaller-${{ env.VERSION }}.zip

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v4
        with:
          name: THJInstaller-ZIP
          path: output/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: output/THJInstaller-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
